# Generated by Django 5.0.3 on 2024-04-09 19:37

from django.db import migrations


def forward_func(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name="Seniors")

def reverse_func(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.delete(name="Seniors")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
