# Generated by Django 5.0.3 on 2024-04-08 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the task title', max_length=50, verbose_name='Task title')),
                ('description', models.TextField(help_text='Enter the task description', max_length=500, verbose_name='Task description')),
                ('due_date', models.DateField(help_text='Choose the task due date', verbose_name='Task due date')),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('NORMAL', 'NORMAL'), ('HIGH', 'HIGH')], help_text='Choose the task priority', max_length=20, verbose_name='Task priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Task creation date')),
                ('difficulty', models.CharField(choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], help_text='Choose the task difficulty', max_length=20, verbose_name='Task difficulty')),
                ('state', models.CharField(choices=[('Completed', 'Complete'), ('Not Done', 'Not Done')], default='Not Done', max_length=20, verbose_name='Task state')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Task completion date')),
                ('assigned_to', models.ManyToManyField(blank=True, help_text='Choose the task assigned to', null=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Task assigned to')),
                ('created_by', models.ForeignKey(help_text='Choose the task created by', on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='Task created by')),
                ('project', models.ForeignKey(blank=True, help_text='Choose the task project', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Task project')),
            ],
        ),
    ]
