# Generated by Django 5.0.3 on 2024-04-02 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Choose the task project', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Task project'),
        ),
    ]
